# Generated by Django 5.2.5 on 2025-08-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('exchange', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('symbol_name', models.CharField(max_length=30)),
                ('symbol_industry', models.CharField(max_length=30)),
                ('symbol_sector', models.CharField(max_length=30)),
                ('scan_source', models.CharField(max_length=5)),
                ('scan_name', models.CharField(max_length=30)),
                ('scan_result', models.BooleanField(default=False)),
                ('scan_cob_date', models.DateField(auto_now_add=True)),
                ('scan_cob_time', models.TimeField(auto_now_add=True)),
                ('scan_run_date', models.DateField(auto_now_add=True)),
                ('scan_run_time', models.TimeField(auto_now_add=True)),
                ('igsymbol', models.CharField(max_length=10)),
                ('cmcsymbol', models.CharField(max_length=10)),
                ('tvsymbol', models.CharField(max_length=10)),
            ],
        ),
    ]
